"""Evaluate the Audio_Detector on the Adversarial_Suite (task 4.13).

Implements R7.2 / R7.3 / R7.4: walk the four R7.1 categories
(``horns``, ``fireworks``, ``tire_blowouts``, ``airbrakes``), run the
active checkpoint via :func:`backend.audio_model.inference.predict` on
every non-placeholder clip, compute a per-category false-positive rate
(``count(event=="CRASH") / count(real clips)``), and emit a JSON report
to ``reports/adversarial_<git_sha>.json``.

The expected label for every adversarial clip is ``noise``; any
``event == "CRASH"`` prediction therefore counts as a false positive.

Exit codes
----------
* ``0`` — report written, no per-category FPR exceeds 0.10
* ``0`` — every category is placeholder-only (no real clips yet); a
  clear stderr note is emitted instead of failing CI on a stubbed corpus
* ``1`` — fatal pre-flight error (manifest missing/unparseable, etc.)
* ``1`` — any per-category FPR > 0.10 (offending categories listed on
  stderr per R7.4)

CLI surface
-----------
``python -m backend.audio_model.evaluate_adversarial
    [--checkpoint PATH] [--manifest PATH] [--out PATH] [--git-sha SHA]``

Reuses :func:`backend.audio_model._eval_helpers.compute_checkpoint_sha256`
so the report's ``checkpoint_sha256`` is generated by the same code path
that stamps the real-world eval reports (R1.4).
"""

from __future__ import annotations

import argparse
import json
import logging
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# Allow both ``python -m backend.audio_model.evaluate_adversarial`` and
# direct invocation as a script.
if __name__ == "__main__" and __package__ in (None, ""):
    _REPO_ROOT = Path(__file__).resolve().parents[2]
    if str(_REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(_REPO_ROOT))

from backend.audio_model import inference  # noqa: E402
from backend.audio_model._eval_helpers import compute_checkpoint_sha256  # noqa: E402

LOG = logging.getLogger("evaluate_adversarial")

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CHECKPOINT = REPO_ROOT / "backend" / "audio_model" / "crash_detector.pth"
DEFAULT_MANIFEST = REPO_ROOT / "data" / "adversarial" / "manifest.json"
DEFAULT_REPORTS_DIR = REPO_ROOT / "reports"

#: R7.1 fixed category set. Hard-coded rather than inferred from the
#: manifest so an accidental rename or extra key in ``manifest.json``
#: cannot silently change the report shape.
CATEGORIES: tuple[str, ...] = ("horns", "fireworks", "tire_blowouts", "airbrakes")

#: R7.3 threshold. Per-category FPR strictly greater than this value
#: causes a non-zero exit per R7.4.
FPR_THRESHOLD: float = 0.10

#: Schema version of the JSON report shape this module emits. Bump on
#: any breaking change (semver MAJOR).
SCHEMA_VERSION: str = "1.0.0"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="evaluate_adversarial.py",
        description=(
            "Evaluate the active Audio_Detector checkpoint on the "
            "Adversarial_Suite and emit per-category false-positive "
            "rates (R7.2, R7.3, R7.4)."
        ),
    )
    parser.add_argument(
        "--checkpoint",
        type=Path,
        default=None,
        help=(
            "Audio_Detector checkpoint (default: "
            "backend/audio_model/crash_detector.pth)"
        ),
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="Adversarial manifest (default: data/adversarial/manifest.json)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help=(
            "Report output (default: reports/adversarial_<git_sha>.json)"
        ),
    )
    parser.add_argument(
        "--git-sha",
        dest="git_sha",
        type=str,
        default=None,
        help=(
            "Override git SHA in output filename (default: from "
            "`git rev-parse --short HEAD`)"
        ),
    )
    return parser


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _detect_git_sha(default: str = "unknown") -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
            check=False,
            timeout=5,
        )
    except (FileNotFoundError, subprocess.SubprocessError):
        return default
    if result.returncode != 0:
        return default
    return result.stdout.strip() or default


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _is_placeholder(row: dict[str, Any]) -> bool:
    """A row is treated as a placeholder when ``is_placeholder`` is true.

    ``_regenerate_placeholders.py`` (task 4.12) writes ``True`` for every
    synthetic stub clip; real clips ingested via
    ``scripts/curate_adversarial.py`` write ``False``. Missing values are
    conservatively treated as real so a malformed manifest does not
    accidentally suppress the FPR check.
    """
    return bool(row.get("is_placeholder", False))


def _evaluate_clip(clip_path: Path) -> bool:
    """Return ``True`` iff the active model flags ``clip_path`` as ``CRASH``.

    The Adversarial_Suite is entirely non-crash audio (R7.1), so any
    ``event == "CRASH"`` decision is a false positive.
    """
    result = inference.predict(str(clip_path))
    return result.get("event") == "CRASH"


# ---------------------------------------------------------------------------
# Top-level driver
# ---------------------------------------------------------------------------


def run(args: argparse.Namespace) -> int:
    """Top-level driver. Returns the process exit code (0 / 1)."""
    git_sha = args.git_sha or _detect_git_sha()
    checkpoint = (args.checkpoint or DEFAULT_CHECKPOINT).resolve()
    manifest_path = (args.manifest or DEFAULT_MANIFEST).resolve()
    out_path = (
        args.out or (DEFAULT_REPORTS_DIR / f"adversarial_{git_sha}.json")
    ).resolve()

    # --- Pre-flight: manifest ---
    if not manifest_path.exists():
        print(
            f"FATAL: adversarial manifest not found at {manifest_path}",
            file=sys.stderr,
        )
        return 1
    try:
        with manifest_path.open("r", encoding="utf-8") as fh:
            manifest = json.load(fh)
    except (OSError, json.JSONDecodeError) as exc:
        print(
            f"FATAL: adversarial manifest at {manifest_path} failed to "
            f"parse: {type(exc).__name__}: {exc}",
            file=sys.stderr,
        )
        return 1

    # --- Pre-flight: checkpoint sha256 (best effort) ---
    # The active checkpoint may be absent in some sandboxes (e.g. CI
    # caches not yet warmed); inference.predict() has its own
    # missing-checkpoint stub fallback, so we record an empty hash and
    # carry on. The pre-flight check still catches genuine read errors.
    checkpoint_id = checkpoint.name
    checkpoint_sha = ""
    if checkpoint.exists():
        try:
            checkpoint_sha = compute_checkpoint_sha256(checkpoint)
        except OSError as exc:
            print(
                f"FATAL: failed to read checkpoint at {checkpoint}: "
                f"{type(exc).__name__}: {exc}",
                file=sys.stderr,
            )
            return 1

    # --- Walk each category ---
    categories = manifest.get("categories") or {}
    per_category: dict[str, dict[str, Any]] = {}
    overall_fp = 0
    overall_n = 0
    offending: list[tuple[str, float]] = []
    any_real_clips = False

    for category in CATEGORIES:
        rows = categories.get(category) or []
        n_placeholder = sum(1 for r in rows if _is_placeholder(r))
        real_rows = [r for r in rows if not _is_placeholder(r)]
        n_clips = 0
        n_fp = 0

        for row in real_rows:
            filename = row.get("filename")
            if not filename:
                LOG.warning(
                    "skipping %s row without filename: %r", category, row
                )
                continue
            clip_path = manifest_path.parent / category / filename
            try:
                is_crash = _evaluate_clip(clip_path)
            except Exception as exc:  # noqa: BLE001
                # Single bad clip never aborts the run — it just goes
                # uncounted. Mirrors the per-clip resilience contract
                # used by evaluate_real_world.py (R1.6).
                LOG.warning(
                    "predict failed for %s/%s (%s); excluding from FPR",
                    category,
                    filename,
                    exc,
                )
                continue
            n_clips += 1
            if is_crash:
                n_fp += 1

        if n_clips > 0:
            any_real_clips = True
            fpr = n_fp / n_clips
        else:
            fpr = 0.0

        per_category[category] = {
            "n_clips": n_clips,
            "n_false_positives": n_fp,
            "fpr": fpr,
            "n_placeholder_skipped": n_placeholder,
        }
        overall_fp += n_fp
        overall_n += n_clips
        if n_clips > 0 and fpr > FPR_THRESHOLD:
            offending.append((category, fpr))

    overall_fpr = (overall_fp / overall_n) if overall_n > 0 else 0.0

    # --- Emit report ---
    report = {
        "schema_version": SCHEMA_VERSION,
        "evaluated_at_iso8601": _utc_now_iso(),
        "git_sha": git_sha,
        "checkpoint_id": checkpoint_id,
        "checkpoint_sha256": checkpoint_sha,
        "per_category": per_category,
        "overall_fpr": overall_fpr,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(report, sort_keys=True, indent=2) + "\n",
        encoding="utf-8",
    )
    LOG.info(
        "evaluated %d real clips; overall FPR=%.4f; report at %s",
        overall_n,
        overall_fpr,
        out_path,
    )

    # --- Exit decision ---
    if not any_real_clips:
        # Corpus is fully stubbed (task 4.12 placeholders only). Don't
        # let a green CI fail simply because the curation work hasn't
        # landed yet.
        print(
            "no real adversarial clips available, skipping FPR threshold "
            f"check (manifest={manifest_path})",
            file=sys.stderr,
        )
        return 0

    if offending:
        print(
            "FAIL: per-category FPR exceeded "
            f"{FPR_THRESHOLD:.2f}:",
            file=sys.stderr,
        )
        for category, fpr in offending:
            print(f"  {category}: fpr={fpr:.4f}", file=sys.stderr)
        return 1

    return 0


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)s | %(name)s | %(message)s",
    )
    parser = build_parser()
    args = parser.parse_args(argv)
    return run(args)


if __name__ == "__main__":  # pragma: no cover - module entry point
    sys.exit(main())
